/**
 * Mouse Dictionary (https://github.com/wtetsu/mouse-dictionary/)
 * Copyright 2018-present wtetsu
 * Licensed under MIT
 */

// Registry of bundled dictionary packs (language pairs). Each pack points to a
// metadata file generated by tools/make_dict.js listing its lookup shards.

import type { DictionaryPack } from "../types";

export const DICTIONARY_PACKS: DictionaryPack[] = [
  { id: "en-ja", metaFile: "/data/dict.json" },
  { id: "en-ar", metaFile: "/data/dict-en-ar.json" },
  { id: "ja-ar", metaFile: "/data/dict-ja-ar.json" },
];

export const DEFAULT_PACK_IDS = ["en-ja"];

export const packIdsFromSettings = (packs: string[] | undefined): string[] => {
  const valid = (packs ?? DEFAULT_PACK_IDS).filter((id) => DICTIONARY_PACKS.some((p) => p.id === id));
  return valid.length > 0 ? valid : DEFAULT_PACK_IDS;
};

// Join two descriptions of the same headword coming from different packs.
// Values that are not strings (e.g. prototype members leaked by key lookups
// such as "constructor") are treated as absent.
export const mergeDescriptions = (existing: unknown, incoming: unknown): string => {
  const a = typeof existing === "string" ? existing : "";
  const b = typeof incoming === "string" ? incoming : "";
  if (!a) {
    return b;
  }
  if (!b || a === b || a.includes(b)) {
    return a;
  }
  if (b.includes(a)) {
    return b;
  }
  return `${a} / ${b}`;
};
