/**
 * Mouse Dictionary (https://github.com/wtetsu/mouse-dictionary/)
 * Copyright 2018-present wtetsu
 * Licensed under MIT
 */

// Registry of bundled dictionary packs (language pairs). Each pack points to a
// metadata file generated by tools/make_dict.js listing its lookup shards.

import type { DictionaryPack } from "../types";

export const DICTIONARY_PACKS: DictionaryPack[] = [
  { id: "en-ja", metaFile: "/data/dict.json" },
  { id: "en-ar", metaFile: "/data/dict-en-ar.json" },
  { id: "ja-ar", metaFile: "/data/dict-ja-ar.json" },
];

export const DEFAULT_PACK_IDS = ["en-ja"];

export const packIdsFromSettings = (packs: string[] | undefined): string[] => {
  const valid = (packs ?? DEFAULT_PACK_IDS).filter((id) => DICTIONARY_PACKS.some((p) => p.id === id));
  return valid.length > 0 ? valid : DEFAULT_PACK_IDS;
};

// Join two descriptions of the same headword coming from different packs.
export const mergeDescriptions = (existing: string | undefined, incoming: string): string => {
  if (!existing) {
    return incoming;
  }
  if (!incoming || existing === incoming || existing.includes(incoming)) {
    return existing;
  }
  if (incoming.includes(existing)) {
    return incoming;
  }
  return `${existing} / ${incoming}`;
};
